credentials:
  root:
    user: root
    password: password
    host: "%"

tls:
  useSelfSigned: true

initDB:
  dump:
    name: francetravail.sql
    path: /var/lib/mysql/francetravail.sql
    options:
      includeSchemas: true
    persistentVolumeClaim: "pvc-datascientest"
service:
  type: "NodePort"

serverInstances: "1"

podSpec:
  containers:
  - name: mysql
    resources:
      requests:
        memory: "1048Mi"  # adapt to your needs
        cpu: "500m"      # adapt to your needs
      limits:
        memory: "2192Mi"  # adapt to your needs
        cpu: "1000m"      # adapt to your needs

#datadirVolumeClaimTemplate:
#  accessModes:
#  resources:
#    requests:
#      storage: