apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: sql-pv
  hostPath:
    path: C:/Users/medsa/Desktop/V2/jun24_cde_job-market/kubernetes/Data