apiVersion: v1
kind: Service
metadata:
  name: sqlclusterip
  labels:
    app: sqldb
spec:
  type: NodePort  
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30000
  selector:
    app: sqldb 