apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqldb
spec:
  selector:
    matchLabels:
      app: sqldb
  serviceName: sqldb
  replicas: 1
  template:
    metadata:
      labels:
        app: sqldb
    spec:
      containers:
        - name: sqldb
          image: docker.io/mysql:latest
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: francetravail
          volumeMounts:
            - name: sql-pvc
              mountPath: /var/lib/mysql
      volumes:
        - name: sql-pvc
          persistentVolumeClaim:
            claimName: pvc-datascientest

                  
